name: integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn
      - run: yarn integration
