name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn add solhint
      - run: yarn lint
