on: [push, pull_request]

name: test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
      - run: yarn

      - uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
  
      - run: forge test --fork-url https://eth.llamarpc.com
